
#spring.datasource.url=jdbc:h2:mem:bank
#spring.h2.console.enabled=true

server:
  port: 8383
  servlet:
    context-path: /ebanking/api/v1
  error:
    path: /user/error
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebank
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    generate-ddl: true
